robot_description: "robot_description"
trajectory_operator_plugin_name: "moveit_hybrid_planning/SimpleSampler"
local_constraint_solver_plugin_name: "curobo_hybrid_planning_plugins/CuroboMpcLocalSolver"
local_planning_frequency: 10.0
global_solution_topic: "global_trajectory"
local_solution_topic: "/forward_position_controller/commands"
local_solution_topic_type: "std_msgs/Float64MultiArray"
publish_joint_positions: true
publish_joint_velocities: false
group_name: "ur_manipulator"
monitored_planning_scene_topic: "/monitored_planning_scene"
collision_object_topic: "/collision_object"
joint_states_topic: "/moveit_joint_states"
hybrid_mpc_tip_link: "TCP_point"
hybrid_mpc_step_dt: 0.03
hybrid_mpc_service_timeout_sec: 10.0
hybrid_mpc_step_service: "/unified_planner/mpc_step"
hybrid_mpc_reset_service: "/unified_planner/mpc_reset"
